{{- if not .Values.existingConfig.name  -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-query-exporter.configName" . }}
  labels: {{- include "mongodb-query-exporter.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    {{ .Values.config | nindent 4}}
{{- end -}}
