{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-query-exporter.secretName" . }}
  labels: {{- include "mongodb-query-exporter.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.mongodb }}
  {{- range $key, $value := .Values.mongodb }}
    MDBEXPORTER_SERVER_{{ $key }}_MONGODB_URI: "{{ $value | b64enc }}"
  {{- end }}
  {{- end }}
{{- end -}}
